name = "order-ieeja"
compatibility_date = "2025-07-18"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "ORDERS_DB"
database_name = "order_ieeja_orders"
database_id = "0eaea965-4467-4aee-89a9-28aed83e4c79"
